# Generated by Django 4.0.4 on 2022-10-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
